### PR TITLE
Add show notes for episode 041.

### PR DESCRIPTION
**Pull request by kenguest**

### CODE REVIEW

**Comment by SammyK** [comment]
Thanks so much for the PR @kenguest! @chris48s already submitted a PR for episode 41 but I did my best to merge both of your show notes into one. :)

https://www.phproundtable.com/episode/the-php-framework-interop-group-past-present-future

**Comment by kenguest** [comment]
You're very welcome - I hope you like the idea of me linking in to close to the near exact spot in the recording on youtube for each time-offset/citation; thought it would help with the accuracy :D 

Doing the show notes is just my way of saying "Thanks" for running/managing a very entertaining and useful podcast ;-)

**Comment by SammyK** [comment]
I do like that indeed - thanks! :)

**Comment by chris48s** [comment]
> Doing the show notes is just my way of saying "Thanks"

I'm mainly doing it for the groupies :sunglasses:

**Comment by SammyK** [comment]
Haha!

**Pull request merged**
