### PR TITLE
027

### PR DESCRIPTION
**Pull request by ahuggins**
Took an easy one to knock out...the Laracon episode, it's only about two minutes before technical difficulties begin happening and the whole there is no more content.

### CODE REVIEW

**Comment by SammyK** [comment]
Thanks @ahuggins! There is a full episode for this in the [audio-only version](https://php-roundtable.s3.amazonaws.com/episodes/027-laracon-us-2015.m4a). It's a bit longer. Lol.

**Comment by ahuggins** [comment]
Cool, I’ll work on that and update it sometime soon. Thought I could get one out of the way easy lol.

Should a link be provided to the audio version you sent me? 

Andy

**Comment by SammyK** [comment]
Haha. You can't get off that easy! :) I'm actually going to be adding a feature to the site to play the audio version. :)

**Comment by chris48s** [comment]
> Should a link be provided to the audio version you sent me?

There are links to the audio versions of every podcast in the RSS feed: http://feeds.feedburner.com/PhpRoundtable

> I'm actually going to be adding a feature to the site to play the audio version

I've never watched the video versions myself and I've always found it a bit strange that the audio versions aren't conveniently linked on the website, so :thumbsup: on that.

**Pull request closed without merging**
